- name: set package list
  set_fact:
    pkgs:
      - etckeeper
      - vanilla-gnome-desktop
      - npm
      - ranger
#      - python
#      - maven
#      - groovy
      - coreutils
#      - docker
      - bash-completion
#      - helm
#      - kubectx
#      - sbt
#      - mtr
      - docker
      - python3-pip
      - jq
      - vagrant
#      - arch-wiki-lite
#      - tilda
#      - lsof
#      - usbutils
#      - base-devel
#      - gnome-tweaks
#      - xorg
#      - xf86-video-intel
#      - gdm
#      - telegram-desktop
#      - openvpn
#      - networkmanager-openvpn
#      - xca
#      - audacity
#      - bluez-utils
#      - dconf-editor
      - feh
#      - virt-manager
#      - transmission-gtk
#      - zathura
#      - zathura-pdf-poppler
#      - zathura-djvu
#      - cockpit
#      - cockpit-dashboard
#      - ebtables
#      - dnsmasq
      - dmidecode
      - lshw
#      - ovmf
      - powertop
#      - cmake
#      - nasm
#      - acpica
#      - acpi_call
#      - looking-glass
#      - bind-tools
      - iotop
      - ruby
#      - ruby-bundler
#      - glibc
#      - iasl
#      - subversion
#      - nvidia-prime
      - copyq
      - vim
      - guake
#      - usbutils
      - ripgrep
#      - go
#      - protobuf
#      - cmus
#      - alsa-utils
#      - noto-fonts-emoji
      - ncdu
#      - realtime-privileges
#      - kdenlive

- name: install apt packages
  become: yes
  apt:
    name: "{{ pkgs }}"
    state: present
  register: xxx

# - debug: msg={{ xxx.stdout.split('\n')[:-1] }}
