- name: copy functions' definitions
  become: yes
  synchronize:
    src: etc/profile.d/
    dest: /etc/profile.d

- name: create kubectl aliases
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
    dest: /etc/profile.d/kubectl_aliases_by_ahmetb_superhero.sh

- name: create .bash_profile
  become: no
  file:
    path: ~/.bash_profile
    state: file
  tags:
    - bash_profile

- name: configure .bash_profile
  lineinfile:
    path: ~/.bash_profile
    regexp: '^for i in /etc/profile.d/'
    line: 'for i in /etc/profile.d/*; do . $i; done'
  tags:
    - bash_profile
