- name: install taps
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - adoptopenjdk/openjdk

- name: install casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  tags:
    - casks
  with_items:
    - adoptopenjdk8
    - iterm2
    - vagrant
    - virtualbox
    - macdown
#    - docker

- name: install brew packages
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - ranger
    - python
    - node
    - maven
    - groovy
    - gpg
    - coreutils
#    - docker
    - podman
    - iproute2mac
    - tomcat
    - tomcat@8
    - bash-completion
    - helm
    - kubectx
    - sbt
    - mtr
    - watch
    - sonar-scanner

- name: fix mtr
  shell: |
    for i in $(brew list mtr | grep sbin/mtr); do ln $i /usr/local/bin/$(basename $i); done
