- name: install taps
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - adoptopenjdk/openjdk
    - warrensbox/tap/tfswitch

- name: install casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  tags:
    - casks
  with_items:
    - adoptopenjdk8
    - iterm2
#    - vagrant
#    - virtualbox
    - macdown
    - docker

- name: install brew packages
  tags:
    - homebrew
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - awscli
    - ranger
    - python
    - node
    - maven
    - groovy
    - gpg
    - coreutils
    - docker
    - iproute2mac
    - tomcat
    - tomcat@8
    - bash-completion
    - helm
    - kubectx
    - sbt
    - mtr
    - watch
    - sonar-scanner
    - pass
    - pinentry-mac
    - insomnia
    - charles
    - ripgrep
    - jq
    - scrcpy
    - vault

- name: fix mtr
  become: yes
  tags: mtr
  shell: |
    for i in $(brew list mtr | grep sbin/mtr); do ln $i /usr/local/bin/$(basename $i); done
