- name: install casks
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - adoptopenjdk/openjdk

- name: install casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  tags:
    - casks
  with_items:
    - adoptopenjdk8
    - iterm2
    - vagrant
    - virtualbox

- name: install brew packages
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - ranger
    - python
    - node
    - maven
    - groovy
    - gpg
    - coreutils
    - docker
