- include: bash.yml
  tags:
    - bash

- include: brew.yml
  when: ansible_distribution == "MacOSX"
  tags:
    - brew

- include: pacman.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - pacman

- include: arch.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - arch

- include: apt.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- include: npm.yml
  tags:
    - npm

- include: ssh_key.yml
  tags:
    - ssh_key

- include: gem.yml
  tags:
    - gem

- include: pip.yml
  tags:
    - pip
