- include: bash.yml
  tags:
    - bash

- include: brew.yml
  tags:
    - brew

- include: npm.yml
  tags:
    - npm

- include: ssh_key.yml
  tags:
    - ssh_key

- include: gem.yml
  tags:
    - gem

