- import_tasks: bash.yml
  tags:
    - bash

- import_tasks: brew.yml
  when: ansible_distribution == "MacOSX"
  tags:
    - brew

- import_tasks: pacman.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - pacman

- import_tasks: arch.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - arch

- import_tasks: apt.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- import_tasks: npm.yml
  tags:
    - npm

- import_tasks: ssh_key.yml
  tags:
    - ssh_key

- import_tasks: gem.yml
  tags:
    - gem

- import_tasks: pip.yml
  tags:
    - pip

- import_tasks: gpg.yml
  tags:
    - gpg
